import type ElementTypes from "./ElementConfigTypes";

export const elements: Array<any> = [
  // {
  //   name: "Input Style",
  //   children: [
  //     {
  //       text: "Outlined",
  //       name: "outlined",
  //       type: "radio",
  //       values: ["Outlined", "Filled"],
  //       default: "#Outlined",
  //     },
  //   ],
  // },
  // {
  //   name: "Ripple Effect",
  //   children: [
  //     {
  //       text: "",
  //       type: "switch",
  //       default: true,
  //     },
  //   ],
  // },
  {
    name: "General",
    children: [
      {
        text: "Font Family",
        name: "generalFontFamily",
        type: "text",
        default:
          "Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,'Noto Sans',sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol','Noto Color Emoji'",
      },
      {
        text: "Text",
        name: "generalText",
        type: "colour-picker",
        default: "#3F3F46",
        property: "color",
        classes: [
          ".p-autocomplete .p-autocomplete-multiple-container .p-autocomplete-input-token input",
          ".p-autocomplete .p-autocomplete-multiple-container .p-autocomplete-token",
          ".p-autocomplete .p-autocomplete-multiple-container .p-autocomplete-token.p-focus",
          ".p-autocomplete-panel",
          ".p-autocomplete-panel .p-autocomplete-items .p-autocomplete-item",
          ".p-autocomplete-panel .p-autocomplete-items .p-autocomplete-item-group",
          ".p-datepicker",
          ".p-datepicker .p-datepicker-header",
          ".p-datepicker .p-datepicker-header .p-datepicker-title .p-datepicker-year,\n.p-datepicker .p-datepicker-header .p-datepicker-title .p-datepicker-month",
          ".p-datepicker table td.p-datepicker-today>span",
          ".p-cascadeselect-panel",
          ".p-cascadeselect-panel .p-cascadeselect-items .p-cascadeselect-item",
          ".p-checkbox .p-checkbox-box",
          ".p-chips .p-chips-multiple-container .p-chips-token",
          ".p-chips .p-chips-multiple-container .p-chips-token.p-focus",
          ".p-chips .p-chips-multiple-container .p-chips-input-token input",
          ".p-dropdown-panel",
          ".p-dropdown-panel .p-dropdown-header",
          ".p-dropdown-panel .p-dropdown-items .p-dropdown-item",
          ".p-dropdown-panel .p-dropdown-items .p-dropdown-item-group",
          ".p-dropdown-panel .p-dropdown-items .p-dropdown-empty-message",
          ".p-editor-container .p-editor-toolbar.ql-snow .ql-picker .ql-picker-label:hover",
          ".p-editor-container .p-editor-toolbar.ql-snow .ql-picker.ql-expanded .ql-picker-label",
          ".p-editor-container .p-editor-toolbar.ql-snow .ql-picker.ql-expanded .ql-picker-options .ql-picker-item",
          ".p-editor-container .p-editor-content .ql-editor",
          ".p-editor-container .ql-snow.ql-toolbar button:hover,\n.p-editor-container .ql-snow.ql-toolbar button:focus",
          ".p-inputtext",
          ".p-listbox",
          ".p-listbox .p-listbox-header",
          ".p-listbox .p-listbox-list .p-listbox-item",
          ".p-listbox .p-listbox-list .p-listbox-item-group",
          ".p-listbox .p-listbox-list .p-listbox-empty-message",
          ".p-multiselect.p-multiselect-chip .p-multiselect-token",
          ".p-multiselect-panel",
          ".p-multiselect-panel .p-multiselect-header",
          ".p-multiselect-panel .p-multiselect-items .p-multiselect-item",
          ".p-multiselect-panel .p-multiselect-items .p-multiselect-item-group",
          ".p-multiselect-panel .p-multiselect-items .p-multiselect-empty-message",
          ".p-password-panel",
          ".p-radiobutton .p-radiobutton-box",
          ".p-rating .p-rating-item .p-rating-icon",
          ".p-selectbutton .p-button",
          ".p-selectbutton .p-button:not(.p-disabled):not(.p-highlight):hover",
          ".p-treeselect.p-treeselect-chip .p-treeselect-token",
          ".p-treeselect-panel",
          ".p-treeselect-panel .p-treeselect-items-wrapper .p-treeselect-empty-message",
          ".p-togglebutton.p-button",
          ".p-togglebutton.p-button:not(.p-disabled):not(.p-highlight):hover",
          ".p-datatable .p-datatable-header",
          ".p-datatable .p-datatable-footer",
          ".p-datatable .p-datatable-tfoot>tr>td",
          ".p-datatable .p-sortable-column:not(.p-highlight):hover",
          ".p-datatable .p-datatable-tbody>tr",
          ".p-datatable.p-datatable-hoverable-rows .p-datatable-tbody>tr:not(.p-highlight):hover",
          ".p-dataview .p-dataview-header",
          ".p-dataview .p-dataview-content",
          ".p-dataview .p-dataview-footer",
          ".p-column-filter-overlay",
          ".p-column-filter-overlay .p-column-filter-row-items .p-column-filter-row-item",
          ".p-column-filter-overlay-menu .p-column-filter-operator",
          ".fc.fc-unthemed .fc-view-container th",
          ".fc.fc-unthemed .fc-view-container td.fc-widget-content",
          ".fc.fc-unthemed .fc-toolbar .fc-button.fc-dayGridMonth-button,\n.fc.fc-unthemed .fc-toolbar .fc-button.fc-timeGridWeek-button,\n.fc.fc-unthemed .fc-toolbar .fc-button.fc-timeGridDay-button",
          ".fc.fc-unthemed .fc-toolbar .fc-button.fc-dayGridMonth-button:hover,\n.fc.fc-unthemed .fc-toolbar .fc-button.fc-timeGridWeek-button:hover,\n.fc.fc-unthemed .fc-toolbar .fc-button.fc-timeGridDay-button:hover",
          ".fc.fc-theme-standard .fc-view-harness th",
          ".fc.fc-theme-standard .fc-view-harness td",
          ".fc.fc-theme-standard .fc-view-harness .fc-popover .fc-popover-header",
          ".fc.fc-theme-standard .fc-view-harness .fc-popover .fc-popover-body",
          ".fc.fc-theme-standard .fc-toolbar .fc-button.fc-dayGridMonth-button,\n.fc.fc-theme-standard .fc-toolbar .fc-button.fc-timeGridWeek-button,\n.fc.fc-theme-standard .fc-toolbar .fc-button.fc-timeGridDay-button",
          ".fc.fc-theme-standard .fc-toolbar .fc-button.fc-dayGridMonth-button:hover,\n.fc.fc-theme-standard .fc-toolbar .fc-button.fc-timeGridWeek-button:hover,\n.fc.fc-theme-standard .fc-toolbar .fc-button.fc-timeGridDay-button:hover",
          ".p-orderlist .p-orderlist-header",
          ".p-orderlist .p-orderlist-list",
          ".p-orderlist .p-orderlist-list .p-orderlist-item",
          ".p-organizationchart .p-organizationchart-node-content",
          ".p-paginator .p-paginator-first:not(.p-disabled):not(.p-highlight):hover,\n.p-paginator .p-paginator-prev:not(.p-disabled):not(.p-highlight):hover,\n.p-paginator .p-paginator-next:not(.p-disabled):not(.p-highlight):hover,\n.p-paginator .p-paginator-last:not(.p-disabled):not(.p-highlight):hover",
          ".p-paginator .p-paginator-pages .p-paginator-page:not(.p-highlight):hover",
          ".p-picklist .p-picklist-header",
          ".p-picklist .p-picklist-list",
          ".p-picklist .p-picklist-list .p-picklist-item",
          ".p-tree",
          ".p-tree .p-tree-container .p-treenode .p-treenode-content .p-checkbox .p-indeterminate .p-checkbox-icon",
          ".p-treetable .p-treetable-header",
          ".p-treetable .p-treetable-footer",
          ".p-treetable .p-treetable-tfoot>tr>td",
          ".p-treetable .p-sortable-column:not(.p-highlight):hover",
          ".p-treetable .p-treetable-tbody>tr",
          ".p-treetable .p-treetable-tbody>tr>td .p-treetable-toggler+.p-checkbox .p-indeterminate .p-checkbox-icon",
          ".p-treetable.p-treetable-hoverable-rows .p-treetable-tbody>tr:not(.p-highlight):hover",
          ".p-treetable.p-treetable-hoverable-rows .p-treetable-tbody>tr:not(.p-highlight):hover .p-treetable-toggler",
          ".p-accordion .p-accordion-header .p-accordion-header-link",
          ".p-accordion .p-accordion-header:not(.p-highlight):not(.p-disabled):hover .p-accordion-header-link",
          ".p-accordion .p-accordion-header:not(.p-disabled).p-highlight .p-accordion-header-link",
          ".p-accordion .p-accordion-header:not(.p-disabled).p-highlight:hover .p-accordion-header-link",
          ".p-accordion .p-accordion-content",
          ".p-card",
          ".p-fieldset",
          ".p-fieldset .p-fieldset-legend",
          ".p-fieldset.p-fieldset-toggleable .p-fieldset-legend a",
          ".p-panel .p-panel-header",
          ".p-panel .p-panel-content",
          ".p-panel .p-panel-footer",
          ".p-splitter",
          ".p-tabview .p-tabview-panels",
          ".p-confirm-popup",
          ".p-dialog .p-dialog-header",
          ".p-dialog .p-dialog-content",
          ".p-dialog .p-dialog-footer",
          ".p-overlaypanel",
          ".p-sidebar",
          ".p-fileupload .p-fileupload-buttonbar",
          ".p-fileupload .p-fileupload-content",
          ".p-breadcrumb .p-breadcrumb-list li .p-menuitem-link .p-menuitem-text",
          ".p-breadcrumb .p-breadcrumb-list li.p-menuitem-separator",
          ".p-breadcrumb .p-breadcrumb-list li:last-child .p-menuitem-text",
          ".p-contextmenu",
          ".p-contextmenu .p-menuitem>.p-menuitem-content",
          ".p-contextmenu .p-menuitem>.p-menuitem-content .p-menuitem-link",
          ".p-contextmenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-contextmenu .p-menuitem.p-highlight>.p-menuitem-content",
          ".p-contextmenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-megamenu",
          ".p-megamenu .p-menuitem>.p-menuitem-content",
          ".p-megamenu .p-menuitem>.p-menuitem-content .p-menuitem-link",
          ".p-megamenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-megamenu .p-menuitem.p-highlight>.p-menuitem-content",
          ".p-megamenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-megamenu .p-megamenu-panel",
          ".p-megamenu .p-submenu-header",
          ".p-megamenu.p-megamenu-horizontal .p-megamenu-root-list>.p-menuitem>.p-menuitem-content",
          ".p-megamenu.p-megamenu-horizontal .p-megamenu-root-list>.p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-menu",
          ".p-menu .p-menuitem>.p-menuitem-content",
          ".p-menu .p-menuitem>.p-menuitem-content .p-menuitem-link",
          ".p-menu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-menu .p-menuitem.p-highlight>.p-menuitem-content",
          ".p-menu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-menu .p-submenu-header",
          ".p-menubar",
          ".p-menubar .p-menubar-root-list>.p-menuitem>.p-menuitem-content",
          ".p-menubar .p-menubar-root-list>.p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-menubar .p-menuitem>.p-menuitem-content",
          ".p-menubar .p-menuitem>.p-menuitem-content .p-menuitem-link",
          ".p-menubar .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-menubar .p-menuitem.p-highlight>.p-menuitem-content",
          ".p-menubar .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-panelmenu .p-panelmenu-header .p-panelmenu-header-content",
          ".p-panelmenu .p-panelmenu-header .p-panelmenu-header-content .p-panelmenu-header-action",
          ".p-panelmenu .p-panelmenu-header:not(.p-highlight):not(.p-disabled):hover .p-panelmenu-header-content",
          ".p-panelmenu .p-panelmenu-header:not(.p-disabled).p-highlight .p-panelmenu-header-content",
          ".p-panelmenu .p-panelmenu-header:not(.p-disabled).p-highlight:hover .p-panelmenu-header-content",
          ".p-panelmenu .p-panelmenu-content",
          ".p-panelmenu .p-panelmenu-content .p-menuitem>.p-menuitem-content",
          ".p-panelmenu .p-panelmenu-content .p-menuitem>.p-menuitem-content .p-menuitem-link",
          ".p-panelmenu .p-panelmenu-content .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-panelmenu .p-panelmenu-content .p-menuitem.p-highlight>.p-menuitem-content",
          ".p-panelmenu .p-panelmenu-content .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-steps .p-steps-item .p-menuitem-link .p-steps-number",
          ".p-steps .p-steps-item.p-highlight .p-steps-title",
          ".p-tieredmenu",
          ".p-tieredmenu .p-menuitem>.p-menuitem-content",
          ".p-tieredmenu .p-menuitem>.p-menuitem-content .p-menuitem-link",
          ".p-tieredmenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-tieredmenu .p-menuitem.p-highlight>.p-menuitem-content",
          ".p-tieredmenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-text",
          ".p-chip",
          ".p-terminal",
        ],
      },
      {
        text: "Secondary Text",
        name: "generalSecondaryText",
        type: "colour-picker",
        default: "#71717A",
        property: "color",
        classes: [
          ".p-text-secondary",
          ".p-datepicker .p-datepicker-header .p-datepicker-prev,\n.p-datepicker .p-datepicker-header .p-datepicker-next",
          ".p-datepicker .p-timepicker button",
          ".p-cascadeselect .p-cascadeselect-label.p-placeholder",
          ".p-cascadeselect .p-cascadeselect-trigger",
          ".p-dropdown .p-dropdown-label.p-placeholder",
          ".p-dropdown .p-dropdown-trigger",
          ".p-dropdown .p-dropdown-clear-icon",
          ".p-dropdown-panel .p-dropdown-header .p-dropdown-filter-icon",
          ".p-editor-container .p-editor-toolbar.ql-snow .ql-picker .ql-picker-label",
          ".p-inputgroup-addon",
          ".p-float-label>label",
          ".p-input-icon-left>i:first-of-type",
          ".p-input-icon-right>i:last-of-type",
          "::-webkit-input-placeholder",
          ":-moz-placeholder",
          "::-moz-placeholder",
          ":-ms-input-placeholder",
          ".p-listbox .p-listbox-header .p-listbox-filter-icon",
          ".p-multiselect .p-multiselect-label.p-placeholder",
          ".p-multiselect .p-multiselect-trigger",
          ".p-multiselect-panel .p-multiselect-header .p-multiselect-filter-container .p-multiselect-filter-icon",
          ".p-multiselect-panel .p-multiselect-header .p-multiselect-close",
          ".p-selectbutton .p-button .p-button-icon-left,\n.p-selectbutton .p-button .p-button-icon-right",
          ".p-selectbutton .p-button:not(.p-disabled):not(.p-highlight):hover .p-button-icon-left,\n.p-selectbutton .p-button:not(.p-disabled):not(.p-highlight):hover .p-button-icon-right",
          ".p-treeselect .p-treeselect-label.p-placeholder",
          ".p-treeselect .p-treeselect-trigger",
          ".p-togglebutton.p-button .p-button-icon-left,\n.p-togglebutton.p-button .p-button-icon-right",
          ".p-togglebutton.p-button:not(.p-disabled):not(.p-highlight):hover .p-button-icon-left,\n.p-togglebutton.p-button:not(.p-disabled):not(.p-highlight):hover .p-button-icon-right",
          ".p-button.p-button-outlined.p-button-plain",
          ".p-button.p-button-outlined.p-button-plain:enabled:hover",
          ".p-button.p-button-outlined.p-button-plain:enabled:active",
          ".p-button.p-button-text.p-button-plain",
          ".p-button.p-button-text.p-button-plain:enabled:hover",
          ".p-button.p-button-text.p-button-plain:enabled:active",
          ".p-splitbutton.p-button-outlined.p-button-plain>.p-button",
          ".p-splitbutton.p-button-outlined.p-button-plain>.p-button:enabled:hover,\n.p-splitbutton.p-button-outlined.p-button-plain>.p-button:not(button):not(a):not(.p-disabled):hover",
          ".p-splitbutton.p-button-outlined.p-button-plain>.p-button:enabled:active,\n.p-splitbutton.p-button-outlined.p-button-plain>.p-button:not(button):not(a):not(.p-disabled):active",
          ".p-splitbutton.p-button-text.p-button-plain>.p-button",
          ".p-splitbutton.p-button-text.p-button-plain>.p-button:enabled:hover,\n.p-splitbutton.p-button-text.p-button-plain>.p-button:not(button):not(a):not(.p-disabled):hover",
          ".p-splitbutton.p-button-text.p-button-plain>.p-button:enabled:active,\n.p-splitbutton.p-button-text.p-button-plain>.p-button:not(button):not(a):not(.p-disabled):active",
          ".p-carousel .p-carousel-content .p-carousel-prev,\n.p-carousel .p-carousel-content .p-carousel-next",
          ".p-datatable .p-sortable-column .p-sortable-column-icon",
          ".p-datatable .p-sortable-column:not(.p-highlight):hover .p-sortable-column-icon",
          ".p-datatable .p-datatable-tbody>tr>td .p-row-toggler,\n.p-datatable .p-datatable-tbody>tr>td .p-row-editor-init,\n.p-datatable .p-datatable-tbody>tr>td .p-row-editor-save,\n.p-datatable .p-datatable-tbody>tr>td .p-row-editor-cancel",
          ".p-column-filter-menu-button",
          ".p-column-filter-clear-button",
          ".fc.fc-theme-standard .fc-view-harness .fc-popover .fc-popover-header .fc-popover-close",
          ".p-paginator",
          ".p-paginator .p-paginator-first,\n.p-paginator .p-paginator-prev,\n.p-paginator .p-paginator-next,\n.p-paginator .p-paginator-last",
          ".p-paginator .p-paginator-current",
          ".p-paginator .p-paginator-pages .p-paginator-page",
          ".p-tree .p-tree-container .p-treenode .p-treenode-content .p-tree-toggler",
          ".p-tree .p-tree-container .p-treenode .p-treenode-content .p-treenode-icon",
          ".p-tree .p-tree-filter-container .p-tree-filter-icon",
          ".p-treetable .p-sortable-column .p-sortable-column-icon",
          ".p-treetable .p-sortable-column:not(.p-highlight):hover .p-sortable-column-icon",
          ".p-treetable .p-treetable-tbody>tr>td .p-treetable-toggler",
          ".p-card .p-card-subtitle",
          ".p-panel .p-panel-header .p-panel-header-icon",
          ".p-tabview .p-tabview-nav li .p-tabview-nav-link",
          ".p-tabview .p-tabview-nav li:not(.p-highlight):not(.p-disabled):hover .p-tabview-nav-link",
          ".p-dialog .p-dialog-header .p-dialog-header-icon",
          ".p-sidebar .p-sidebar-header .p-sidebar-close,\n.p-sidebar .p-sidebar-header .p-sidebar-icon",
          ".p-breadcrumb .p-breadcrumb-list li .p-menuitem-link .p-menuitem-icon",
          ".p-breadcrumb .p-breadcrumb-list li:last-child .p-menuitem-icon",
          ".p-contextmenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-contextmenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-contextmenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-icon,\n.p-contextmenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-contextmenu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-contextmenu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-megamenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-megamenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-megamenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-icon,\n.p-megamenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-megamenu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-megamenu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-megamenu.p-megamenu-horizontal .p-megamenu-root-list>.p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-megamenu.p-megamenu-horizontal .p-megamenu-root-list>.p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-megamenu.p-megamenu-horizontal .p-megamenu-root-list>.p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-megamenu.p-megamenu-horizontal .p-megamenu-root-list>.p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-menu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-menu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-menu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-icon,\n.p-menu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-menu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-menu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-menubar .p-menubar-root-list>.p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-menubar .p-menubar-root-list>.p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-menubar .p-menubar-root-list>.p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-menubar .p-menubar-root-list>.p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-menubar .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-menubar .p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-menubar .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-icon,\n.p-menubar .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-menubar .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-menubar .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-panelmenu .p-panelmenu-content .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-panelmenu .p-panelmenu-content .p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-panelmenu .p-panelmenu-content .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-icon,\n.p-panelmenu .p-panelmenu-content .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-panelmenu .p-panelmenu-content .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-panelmenu .p-panelmenu-content .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
          ".p-steps .p-steps-item .p-menuitem-link .p-steps-title",
          ".p-tabmenu .p-tabmenu-nav .p-tabmenuitem .p-menuitem-link",
          ".p-tabmenu .p-tabmenu-nav .p-tabmenuitem:not(.p-highlight):not(.p-disabled):hover .p-menuitem-link",
          ".p-tieredmenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-menuitem-icon",
          ".p-tieredmenu .p-menuitem>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-tieredmenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-menuitem-icon,\n.p-tieredmenu .p-menuitem.p-highlight>.p-menuitem-content .p-menuitem-link .p-submenu-icon",
          ".p-tieredmenu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-menuitem-icon,\n.p-tieredmenu .p-menuitem:not(.p-highlight):not(.p-disabled)>.p-menuitem-content:hover .p-menuitem-link .p-submenu-icon",
        ],
      },
      {
        text: "Border Radius",
        name: "generalBorderRadius",
        type: "text",
        default: "#6px",
      },
      {
        text: "Disabled Opacity",
        name: "generalDisabledOpacity",
        type: "text",
        default: "#0.6",
      },
    ],
  },
  {
    name: "Palette",
    children: [
      {
        text: "Primary",
        name: "palettePrimary",
        type: "colour-picker",
        default: "#4F46E5",
      },
      {
        text: "Text on Primary",
        name: "paletteTextOnPrimary",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Highlight Background",
        name: "paletteHighlightBackground",
        type: "colour-picker",
        default: "#EEF2FF",
      },
      {
        text: "Text on Highlight",
        name: "paletteTextOnHighlight",
        type: "colour-picker",
        default: "#312E81",
      },
      {
        text: "Hover Background",
        name: "paletteHoverBackground",
        type: "colour-picker",
        default: "#F4F4F5",
      },
      {
        text: "Error",
        name: "paletteError",
        type: "colour-picker",
        default: "#E24C4C",
      },
    ],
  },
  {
    name: "Surfaces",
    children: [
      {
        text: "Header",
        name: "surfaceHeader",
        type: "colour-picker",
        default: "#FAFAFA",
      },
      {
        text: "Content",
        name: "surfaceContent",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Border",
        name: "surfaceBorder",
        type: "colour-picker",
        default: "#E5E7EB",
      },
    ],
  },
  {
    name: "Forms",
    children: [
      {
        text: "Background",
        name: "formBackground",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Border",
        name: "formBorder",
        type: "colour-picker",
        default: "#D4D4D8",
      },
      {
        text: "Hover Border",
        name: "formHoverBorder",
        type: "colour-picker",
        default: "#D4D4D8",
      },
      {
        text: "Focus Border",
        name: "formFocusBorder",
        type: "colour-picker",
        default: "#6366F1",
      },
      {
        text: "Filled Background",
        name: "formFilledBackground",
        type: "colour-picker",
        default: "#FAFAFA",
      },
    ],
  },
  {
    name: "Buttons",
    children: [
      {
        text: "Secondary Background",
        name: "btnSecondaryBackground",
        type: "colour-picker",
        default: "#64748B",
      },
      {
        text: "Secondary Text",
        name: "btnSecondaryText",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Success Background",
        name: "btnSuccessBackground",
        type: "colour-picker",
        default: "#22C55E",
      },
      {
        text: "Success Text",
        name: "btnSuccessText",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Info Background",
        name: "btnInfoBackground",
        type: "colour-picker",
        default: "#3B82F6",
      },
      {
        text: "Info Text",
        name: "btnInfoText",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Warning Background",
        name: "btnWarningBackground",
        type: "colour-picker",
        default: "#F59E0B",
      },
      {
        text: "Warning Text",
        name: "btnWarningText",
        type: "colour-picker",
        default: "#212529",
      },
      {
        text: "Help Background",
        name: "btnHelpBackground",
        type: "colour-picker",
        default: "#A855F7",
      },
      {
        text: "Help Text",
        name: "btnHelpText",
        type: "colour-picker",
        default: "#FFFFFF",
      },
      {
        text: "Danger Background",
        name: "btnDangerBackground",
        type: "colour-picker",
        default: "#EF4444",
      },
      {
        text: "Danger Text",
        name: "btnDangerText",
        type: "colour-picker",
        default: "#FFFFFF",
      },
    ],
  },
  {
    name: "Messages",
    children: [
      {
        text: "Info",
        name: "msgInfo",
        type: "colour-picker",
        default: "#EFF6FF",
      },
      {
        text: "Success",
        name: "msgSuccess",
        type: "colour-picker",
        default: "#ECFDF5",
      },
      {
        text: "Warning",
        name: "msgWarning",
        type: "colour-picker",
        default: "#FEF3CF",
      },
      {
        text: "Error",
        name: "msgError",
        type: "colour-picker",
        default: "#FEF3CF",
      },
    ],
  },
];
